#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.
#
# Library origin: mattpocock/skills wizard (MIT © 2026 Matt Pocock)
# https://github.com/mattpocock/skills/tree/main/skills/engineering/wizard

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame (no Enter gate).
banner() {
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
}

# stage "Name" — announce a stage and show progress (no screen clear / Enter gate).
stage() {
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — closing summary of everything configured.
finish() {
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
DOCKER_DAEMON_READY=0

# Prefer paths relative to this script (repo root = parent of scripts/).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_HARNESS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CLI_REL="packages/agent-harness/dist/cli.js"

# shellcheck source=lib/user-settings.sh
. "$SCRIPT_DIR/lib/user-settings.sh"

_is_windows() {
  [[ "${OS:-}" == "Windows_NT" ]] || [[ "$(uname -s 2>/dev/null || true)" == MINGW* ]] \
    || [[ "$(uname -s 2>/dev/null || true)" == MSYS* ]] \
    || [[ "$(uname -s 2>/dev/null || true)" == CYGWIN* ]] \
    || command -v powershell.exe >/dev/null 2>&1
}

_node_ok() {
  command -v node >/dev/null 2>&1 || return 1
  node -e "const [M,m]=process.versions.node.split('.').map(Number); process.exit(M>20||(M===20&&m>=3)?0:1)" 2>/dev/null
}

_harness_checkout_ok() {
  local path="$1"
  [[ -n "$path" && -f "$path/package.json" && -d "$path/packages/agent-harness" ]]
}

_npm_cmd() {
  if command -v npm.cmd >/dev/null 2>&1; then
    printf '%s' "npm.cmd"
  elif command -v npm >/dev/null 2>&1; then
    printf '%s' "npm"
  fi
}

_npm_global_bin() {
  local npm prefix
  npm="$(_npm_cmd)"
  [[ -n "$npm" ]] || return 0
  prefix="$("$npm" prefix -g 2>/dev/null || true)"
  prefix="${prefix//$'\r'/}"
  [[ -n "$prefix" ]] || return 0
  if [[ -d "$prefix/bin" ]]; then
    printf '%s' "$prefix/bin"
  else
    printf '%s' "$prefix"
  fi
}

_ensure_npm_global_bin_on_path() {
  local bin
  bin="$(_npm_global_bin)"
  [[ -n "$bin" ]] || return 0
  case ":$PATH:" in
    *":$bin:"*) ;;
    *) export PATH="$bin:$PATH" ;;
  esac
  hash -r 2>/dev/null || true
}

_cli_version() {
  local name="$1" bin candidate
  _ensure_npm_global_bin_on_path
  if command -v "$name" >/dev/null 2>&1; then
    "$name" --version 2>/dev/null && return 0
  fi
  bin="$(_npm_global_bin)"
  if [[ -n "$bin" ]]; then
    for candidate in "$bin/$name" "$bin/$name.cmd" "$bin/$name.exe"; do
      if [[ -e "$candidate" ]]; then
        "$candidate" --version 2>/dev/null && return 0
      fi
    done
  fi
  return 1
}

_codegraph_version() { _cli_version codegraph; }
_gitnexus_version() { _cli_version gitnexus; }

_install_npm_global_package() {
  local display="$1" package="$2" command="$3"
  local existing npm bin ver
  existing="$(_cli_version "$command" || true)"
  existing="${existing//$'\r'/}"
  if [[ -n "$existing" ]]; then
    printf '  %s✓ %s already installed%s (%s)\n' "$GREEN" "$display" "$RESET" "$existing"
    return 0
  fi
  npm="$(_npm_cmd)"
  if [[ -z "$npm" ]]; then
    printf '  %snpm is not on PATH — cannot install %s.%s\n' "$RED" "$display" "$RESET"
    note "Install Node.js (includes npm), then: npm install -g $package"
    SKIPPED+=("$display (npm missing)")
    return 0
  fi
  say "Running npm install -g $package..."
  if ! "$npm" install -g "$package"; then
    printf '  %snpm install -g %s failed.%s\n' "$RED" "$package" "$RESET"
    SKIPPED+=("$display (npm install failed)")
    return 0
  fi
  bin="$(_npm_global_bin)"
  _ensure_npm_global_bin_on_path
  ver="$(_cli_version "$command" || true)"
  ver="${ver//$'\r'/}"
  if [[ -n "$ver" ]]; then
    printf '  %s✓ installed %s%s (%s)\n' "$GREEN" "$display" "$RESET" "$ver"
    [[ -n "$bin" ]] && note "npm global bin: $bin"
  else
    warn "$display installed, but this session cannot find $command --version."
    if [[ -n "$bin" ]]; then
      note "Add $bin to PATH (Windows default: %AppData%\\Roaming\\npm), then open a new terminal."
    else
      note "Ensure the npm global bin directory is on PATH, then open a new terminal."
    fi
    SKIPPED+=("$display PATH (new terminal may be required)")
  fi
}

_warn_gitnexus_license() {
  warn "GitNexus is licensed under PolyForm Noncommercial License 1.0.0."
  note "Free for noncommercial / personal use only. Commercial use of the OSS package needs a separate license from Akon Labs."
  note "License: https://github.com/abhigyanpatwari/GitNexus/blob/main/LICENSE"
  note "Commercial / enterprise: https://akonlabs.com or founders@akonlabs.com"
}

_install_gitnexus_cli() {
  _install_npm_global_package "GitNexus" "gitnexus" "gitnexus"
}

_install_codegraph_cli() {
  _install_npm_global_package "CodeGraph" "@colbymchenry/codegraph" "codegraph"
}

_read_windows_user_env() {
  local name="$1"
  command -v powershell.exe >/dev/null 2>&1 || return 1
  powershell.exe -NoProfile -Command \
    "\$v = [Environment]::GetEnvironmentVariable('$name','User'); if (\$null -eq \$v) { '' } else { [Console]::Out.Write(\$v) }" \
    2>/dev/null | tr -d '\r'
}

_set_windows_user_env() {
  local name="$1" value="$2"
  if ! command -v powershell.exe >/dev/null 2>&1; then
    warn "powershell.exe not found — could not persist $name to the Windows User environment"
    SKIPPED+=("Windows User env $name")
    return 1
  fi
  # Pass the secret via the child process environment — do not interpolate into -Command.
  env "$name=$value" powershell.exe -NoProfile -Command \
    "[System.Environment]::SetEnvironmentVariable('$name', [Environment]::GetEnvironmentVariable('$name'), 'User')" \
    >/dev/null || {
      warn "failed to set Windows User environment variable $name"
      SKIPPED+=("Windows User env $name")
      return 1
    }
  printf '  %s✓ set%s Windows User environment variable %s\n' "$GREEN" "$RESET" "$name"
}

banner "Agent Harness — installation"

# ── 1. Node prerequisites ─────────────────────────────────────────────────
stage "Node prerequisites"
say "The harness CLI needs Node.js 20.3+ and npm."
if _node_ok; then
  printf '  %s✓ Found%s %s and npm %s\n' "$GREEN" "$RESET" "$(node -v)" "$(npm -v 2>/dev/null || echo '?')"
else
  warn "Node.js 20.3+ is missing or too old."
  if _is_windows; then
    step "Install with WinGet (recommended), or use the Node download page."
    note "winget install OpenJS.NodeJS.LTS"
    if confirm "Open the Node.js download page in your browser?"; then
      open_url "https://nodejs.org/en/download"
    fi
    say "After installing, close this terminal and re-run the wizard so PATH updates."
  else
    step "Install Node 20.3+ from your package manager or https://nodejs.org"
    open_url "https://nodejs.org/en/download"
  fi
  pause "Press Enter once node -v shows v20.3 or newer"
  if ! _node_ok; then
    warn "Still no usable Node — fix PATH / install, then re-run this wizard."
    exit 1
  fi
fi

# ── 2. Required Docker execution runtime ───────────────────────────────────
stage "Docker readiness"
say "Production execution is Docker-only. Local worktrees and generated per-run images are retired."
note "This stage never silently installs Docker Desktop / docker.io."
note "Bridge networking provides filesystem isolation, not an egress-proof boundary."
_docker_ready() {
  command -v docker >/dev/null 2>&1 || return 1
  local info
  if ! info="$(docker info 2>&1)"; then
    return 1
  fi
  if printf '%s' "$info" | grep -qi 'OSType:[[:space:]]*windows' \
    && ! printf '%s' "$info" | grep -qi 'OSType:[[:space:]]*linux'; then
    warn "Docker appears to be in Windows container mode — switch to Linux containers."
    return 1
  fi
  return 0
}
if _docker_ready; then
  printf '  %s✓ docker info succeeded%s\n' "$GREEN" "$RESET"
  DOCKER_DAEMON_READY=1
  note "The maintained worker image will be rebuilt and probed after project registration."
else
  warn "Docker is required, but the CLI/daemon is not ready."
  if _is_windows; then
    note "Use Docker Desktop + WSL2 backend + Linux containers, then re-run setup."
  else
    note "Ensure your user can access the Docker daemon (docker group / socket permissions)."
  fi
  exit 1
fi

# ── 3. Build this checkout ────────────────────────────────────────────────
stage "Build this checkout"
HARNESS_ROOT="${HARNESS_ROOT:-$DEFAULT_HARNESS_ROOT}"
# Skip asking when the script's parent checkout is already valid (includes LLM-Rules-Skills).
if _harness_checkout_ok "$HARNESS_ROOT"; then
  note "Using checkout: $HARNESS_ROOT"
else
  ask HARNESS_ROOT "Path to the LLM-Rules-Skills checkout:"
  [[ -z "$HARNESS_ROOT" ]] && HARNESS_ROOT="$DEFAULT_HARNESS_ROOT"
  HARNESS_ROOT="${HARNESS_ROOT/#\~/$HOME}"
  if ! _harness_checkout_ok "$HARNESS_ROOT"; then
    warn "That path does not look like this repo (missing package.json or packages/agent-harness)."
    exit 1
  fi
fi
CLI="$HARNESS_ROOT/$CLI_REL"
say "Running npm install && npm run build..."
(
  cd "$HARNESS_ROOT"
  npm install
  npm run build
)
if [[ ! -f "$CLI" ]]; then
  warn "Build finished but $CLI is missing — registration will fail."
  exit 1
fi
printf '  %s✓ built%s %s\n' "$GREEN" "$RESET" "$CLI"

# ── 4. Cursor API key (Windows User env — never .env) ─────────────────────
stage "Cursor API key"
say "The dashboard does not need a key. Real Cursor runs use CURSOR_API_KEY."
note "The key is passed into the isolated run container. GITHUB_TOKEN and harness state remain host-only."
EXISTING_KEY="${CURSOR_API_KEY:-}"
if [[ -z "$EXISTING_KEY" ]] && _is_windows; then
  EXISTING_KEY="$(_read_windows_user_env CURSOR_API_KEY || true)"
fi
if [[ -n "$EXISTING_KEY" ]]; then
  printf '  %s✓ Using existing CURSOR_API_KEY%s\n' "$GREEN" "$RESET"
  CURSOR_API_KEY="$EXISTING_KEY"
  if confirm "Replace it with a new key?"; then
    CURSOR_API_KEY=""
  fi
fi
if [[ -z "${CURSOR_API_KEY:-}" ]]; then
  if confirm "Save a Cursor API key now?"; then
    open_url "https://cursor.com/dashboard/api"
    step "Create a user API key, then paste it here."
    ask_secret CURSOR_API_KEY "Paste the Cursor API key:"
  fi
  if [[ -z "${CURSOR_API_KEY:-}" ]]; then
    note "No key saved. You can still open the dashboard and run deterministic checks."
  fi
fi
if [[ -n "${CURSOR_API_KEY:-}" ]]; then
  export CURSOR_API_KEY
  if _is_windows; then
    USER_KEY="$(_read_windows_user_env CURSOR_API_KEY || true)"
    if [[ "$USER_KEY" != "$CURSOR_API_KEY" ]]; then
      _set_windows_user_env CURSOR_API_KEY "$CURSOR_API_KEY"
      note "New terminals pick it up automatically. Restart any running harness/ui after changes."
    fi
  else
    note "Non-Windows: export CURSOR_API_KEY in your shell profile for persistence."
    note "  export CURSOR_API_KEY=…   # e.g. ~/.bashrc or ~/.zshrc"
    SKIPPED+=("persist CURSOR_API_KEY in your shell profile")
  fi
fi

# ── 5. Target project + register ──────────────────────────────────────────
stage "Target project"
say "Registers the repo in harness home (config stays outside the project)."
ask PROJECT_PATH "Absolute path to the target project:"
PROJECT_PATH="${PROJECT_PATH/#\~/$HOME}"
if [[ -z "$PROJECT_PATH" ]]; then
  warn "A project path is required."
  exit 1
fi
if [[ ! -d "$PROJECT_PATH" ]]; then
  if confirm "Directory does not exist. Create it?"; then
    mkdir -p "$PROJECT_PATH"
  else
    exit 1
  fi
fi
note "Project: $PROJECT_PATH"
if [[ -f "$PROJECT_PATH/agent-harness.config.yaml" || -e "$PROJECT_PATH/.agent-harness" ]]; then
  warn "Found leftover repo-local harness files (agent-harness.config.yaml and/or .agent-harness/)."
  note "Legacy repo-local state is unsupported. Archive or remove it after confirming the external registration."
fi
INITIALIZED_GIT_REPO=0
if [[ -e "$PROJECT_PATH/.git" ]]; then
  note "Git repository already present."
elif ! command -v git >/dev/null 2>&1; then
  warn "git is not on PATH — cannot initialize a repository."
  note "Install git, or set git.enabled: false in the harness-home project config."
  SKIPPED+=("git repository (git not installed)")
else
  say "No .git found — initializing a git repository (required for harness runs)."
  if (cd "$PROJECT_PATH" && { git init -b main 2>/dev/null || git init; }); then
    INITIALIZED_GIT_REPO=1
    printf '  %s✓ initialized git repository%s\n' "$GREEN" "$RESET"
  else
    warn "git init failed — fix manually or set git.enabled: false in harness-home config."
    SKIPPED+=("git init in target project")
  fi
fi

say "Registering project..."
if node "$CLI" project add --repository "$PROJECT_PATH"; then
  printf '  %s✓ project registered in harness home%s\n' "$GREEN" "$RESET"
else
  warn "project add reported an error (exit $?)."
  note "If the repository is already registered, that is fine — continue."
  SKIPPED+=("project add (non-zero exit; may already be registered)")
fi
if remembered="$(ah_remember_project "$PROJECT_PATH" 2>/dev/null)"; then
  note "remembered project in $(ah_settings_path)"
else
  warn "could not write user settings at $(ah_settings_path)"
fi
unset remembered
if [[ "$INITIALIZED_GIT_REPO" -eq 1 ]]; then
  if ! git -C "$PROJECT_PATH" config --get user.email >/dev/null 2>&1; then
    git -C "$PROJECT_PATH" config user.email "agent-harness@localhost"
  fi
  if ! git -C "$PROJECT_PATH" config --get user.name >/dev/null 2>&1; then
    git -C "$PROJECT_PATH" config user.name "Agent Harness"
  fi
  git -C "$PROJECT_PATH" add -A
  if [[ -n "$(git -C "$PROJECT_PATH" status --porcelain 2>/dev/null || true)" ]]; then
    if git -C "$PROJECT_PATH" commit -m "chore: initial commit"; then
      git -C "$PROJECT_PATH" branch -M main 2>/dev/null || true
      printf '  %s✓ created initial commit on main%s\n' "$GREEN" "$RESET"
    else
      warn "initial git commit failed — commit manually before Start reflect."
      SKIPPED+=("initial git commit")
    fi
  else
    note "nothing to commit after registration"
  fi
fi

# ── 6. Docker (optional; not a launch gate) ────────────────────────────────
stage "Docker"
if _docker_ready; then
  printf '  %s✓ Docker is ready (Linux containers). Runs use one container each.%s\n' "$GREEN" "$RESET"
else
  warn "Docker is not ready. Fake-agent flows still work; isolated Cursor runs will not."
fi

# ── 7. Repository intelligence ────────────────────────────────────────────
stage "Repository intelligence"
say "Harness structural lookup prefers GitNexus, then falls back to CodeGraph."
note "Both CLIs are optional. Skip either to leave that provider unset."
printf '\n'
_warn_gitnexus_license
if confirm "Install GitNexus now (primary)? Confirm you understand the license terms above."; then
  _install_gitnexus_cli
else
  note "Skipped GitNexus. Install later with: npm install -g gitnexus"
fi
printf '\n'
say "CodeGraph is the fallback structural provider."
note "Needs the codegraph CLI on PATH."
if confirm "Install CodeGraph now (fallback)?"; then
  _install_codegraph_cli
else
  note "Skipped CodeGraph. Install later with: npm install -g @colbymchenry/codegraph"
fi
note "Optional later: Ollama embeddings (packages/agent-harness/scripts/setup-local-embeddings.sh)"

finish
say "Future launches: bash scripts/launch-agent-harness.sh"

if [[ -f "$CLI" && -d "$PROJECT_PATH" ]] && confirm "Open the dashboard now?"; then
  exec bash "$SCRIPT_DIR/launch-agent-harness.sh" "$PROJECT_PATH" --no-pull --no-build
fi
