#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.
#
# Library origin: mattpocock/skills wizard (MIT © 2026 Matt Pocock)
# https://github.com/mattpocock/skills/tree/main/skills/engineering/wizard

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Prefer paths relative to this script (repo root = parent of scripts/).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_HARNESS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CLI_REL="packages/agent-harness/dist/cli.js"

_is_windows() {
  [[ "${OS:-}" == "Windows_NT" ]] || [[ "$(uname -s 2>/dev/null || true)" == MINGW* ]] \
    || [[ "$(uname -s 2>/dev/null || true)" == MSYS* ]] \
    || [[ "$(uname -s 2>/dev/null || true)" == CYGWIN* ]] \
    || command -v powershell.exe >/dev/null 2>&1
}

_node_ok() {
  command -v node >/dev/null 2>&1 || return 1
  node -e "const [M,m]=process.versions.node.split('.').map(Number); process.exit(M>20||(M===20&&m>=3)?0:1)" 2>/dev/null
}

_read_windows_user_env() {
  local name="$1"
  command -v powershell.exe >/dev/null 2>&1 || return 1
  powershell.exe -NoProfile -Command \
    "\$v = [Environment]::GetEnvironmentVariable('$name','User'); if (\$null -eq \$v) { '' } else { [Console]::Out.Write(\$v) }" \
    2>/dev/null | tr -d '\r'
}

_set_windows_user_env() {
  local name="$1" value="$2"
  if ! command -v powershell.exe >/dev/null 2>&1; then
    warn "powershell.exe not found — could not persist $name to the Windows User environment"
    SKIPPED+=("Windows User env $name")
    return 1
  fi
  # Pass the secret via the child process environment — do not interpolate into -Command.
  env "$name=$value" powershell.exe -NoProfile -Command \
    "[System.Environment]::SetEnvironmentVariable('$name', [Environment]::GetEnvironmentVariable('$name'), 'User')" \
    >/dev/null || {
      warn "failed to set Windows User environment variable $name"
      SKIPPED+=("Windows User env $name")
      return 1
    }
  printf '  %s✓ set%s Windows User environment variable %s\n' "$GREEN" "$RESET" "$name"
}

banner "Agent Harness — installation"

# ── 1. Node prerequisites ─────────────────────────────────────────────────
stage "Node prerequisites"
say "The harness CLI needs Node.js 20.3+ and npm."
if _node_ok; then
  note "Found $(node -v) and npm $(npm -v 2>/dev/null || echo '?')"
else
  warn "Node.js 20.3+ is missing or too old."
  if _is_windows; then
    step "Install with WinGet (recommended), or use the Node download page."
    note "winget install OpenJS.NodeJS.LTS"
    if confirm "Open the Node.js download page in your browser?"; then
      open_url "https://nodejs.org/en/download"
    fi
    say "After installing, close this terminal and re-run the wizard so PATH updates."
  else
    step "Install Node 20.3+ from your package manager or https://nodejs.org"
    open_url "https://nodejs.org/en/download"
  fi
  pause "Press Enter once node -v shows v20.3 or newer"
  if ! _node_ok; then
    warn "Still no usable Node — fix PATH / install, then re-run this wizard."
    exit 1
  fi
fi
if _is_windows; then
  note "If PowerShell blocks npm.ps1 (ExecutionPolicy), run once:"
  note "  Set-ExecutionPolicy -Scope CurrentUser RemoteSigned"
  note "Or use npm.cmd / Command Prompt instead."
fi
pause "Continue to build the harness checkout?"

# ── 2. Build this checkout ────────────────────────────────────────────────
stage "Build this checkout"
say "We'll install dependencies and build packages/agent-harness."
HARNESS_ROOT="${HARNESS_ROOT:-$DEFAULT_HARNESS_ROOT}"
ask HARNESS_ROOT "Path to the LLM-Rules-Skills checkout:"
[[ -z "$HARNESS_ROOT" ]] && HARNESS_ROOT="$DEFAULT_HARNESS_ROOT"
# Expand ~ if the human typed it.
HARNESS_ROOT="${HARNESS_ROOT/#\~/$HOME}"
if [[ ! -f "$HARNESS_ROOT/package.json" ]] || [[ ! -d "$HARNESS_ROOT/packages/agent-harness" ]]; then
  warn "That path does not look like this repo (missing package.json or packages/agent-harness)."
  exit 1
fi
CLI="$HARNESS_ROOT/$CLI_REL"
say "Running npm install && npm run build in:"
note "$HARNESS_ROOT"
(
  cd "$HARNESS_ROOT"
  npm install
  npm run build
)
if [[ ! -f "$CLI" ]]; then
  warn "Build finished but $CLI is missing — deploy will fail."
  exit 1
fi
printf '  %s✓ built%s %s\n' "$GREEN" "$RESET" "$CLI"
pause "Continue to the Cursor API key?"

# ── 3. Cursor API key (Windows User env — never .env) ─────────────────────
stage "Cursor API key"
say "Real agent runs need CURSOR_API_KEY. We store it as a Windows User"
say "environment variable (not in .env / not in the repo)."
EXISTING_KEY="${CURSOR_API_KEY:-}"
if [[ -z "$EXISTING_KEY" ]] && _is_windows; then
  EXISTING_KEY="$(_read_windows_user_env CURSOR_API_KEY || true)"
fi
KEEP_KEY=0
if [[ -n "$EXISTING_KEY" ]]; then
  note "A CURSOR_API_KEY is already available in this environment (or User env)."
  if confirm "Keep the existing key?"; then
    CURSOR_API_KEY="$EXISTING_KEY"
    KEEP_KEY=1
  fi
fi
if [[ "$KEEP_KEY" -eq 0 ]]; then
  open_url "https://cursor.com/dashboard/api"
  step "Sign in to the Cursor Dashboard if prompted."
  step "Open API Keys (Dashboard → API Keys)."
  step "Create a user API key, then copy it immediately (it may not be shown again)."
  ask_secret CURSOR_API_KEY "Paste the Cursor API key:"
  if [[ -z "${CURSOR_API_KEY:-}" ]]; then
    warn "No key pasted — agent runs will fail until CURSOR_API_KEY is set."
    SKIPPED+=("CURSOR_API_KEY")
  fi
fi
if [[ -n "${CURSOR_API_KEY:-}" ]]; then
  export CURSOR_API_KEY
  if _is_windows; then
    if confirm "Persist CURSOR_API_KEY to your Windows User environment?"; then
      _set_windows_user_env CURSOR_API_KEY "$CURSOR_API_KEY"
      note "New terminals pick it up automatically. Restart any running harness/ui after changes."
    else
      note "Key exported for this wizard session only."
      SKIPPED+=("persist CURSOR_API_KEY to Windows User env")
    fi
  else
    note "Non-Windows: export CURSOR_API_KEY in your shell profile for persistence."
    note "  export CURSOR_API_KEY=…   # e.g. ~/.bashrc or ~/.zshrc"
    SKIPPED+=("persist CURSOR_API_KEY in your shell profile")
  fi
fi
pause "Continue to choose the target project?"

# ── 4. Target project ─────────────────────────────────────────────────────
stage "Target project"
say "Deploy writes agent-harness.config.yaml and .agent-harness/ into a project folder."
ask PROJECT_PATH "Absolute path to the target project:"
PROJECT_PATH="${PROJECT_PATH/#\~/$HOME}"
if [[ -z "$PROJECT_PATH" ]]; then
  warn "A project path is required."
  exit 1
fi
if [[ ! -d "$PROJECT_PATH" ]]; then
  if confirm "Directory does not exist. Create it?"; then
    mkdir -p "$PROJECT_PATH"
  else
    exit 1
  fi
fi
note "Project: $PROJECT_PATH"
# Deploy defaults to git.enabled: true; Start reflect needs a real git repo.
INITIALIZED_GIT_REPO=0
if [[ -e "$PROJECT_PATH/.git" ]]; then
  note "Git repository already present."
elif ! command -v git >/dev/null 2>&1; then
  warn "git is not on PATH — cannot initialize a repository."
  note "Install git, or set git.enabled: false in agent-harness.config.yaml after deploy."
  SKIPPED+=("git repository (git not installed)")
else
  say "No .git found — initializing a git repository (required for harness runs)."
  if (cd "$PROJECT_PATH" && { git init -b main 2>/dev/null || git init; }); then
    INITIALIZED_GIT_REPO=1
    printf '  %s✓ initialized git repository%s (will commit after deploy so the tree is clean)\n' "$GREEN" "$RESET"
  else
    warn "git init failed — fix manually or set git.enabled: false after deploy."
    SKIPPED+=("git init in target project")
  fi
fi
pause "Continue to optional Ollama embeddings?"

# ── 5. Optional: Ollama ───────────────────────────────────────────────────
stage "Optional — Ollama embeddings"
say "Ollama provides local embeddings (no cloud API key). Deploy can wire it with --ollama."
USE_OLLAMA=0
if confirm "Configure Ollama embeddings during deploy?"; then
  USE_OLLAMA=1
  step "Install Ollama if needed (Windows: winget install Ollama.Ollama, or the download page)."
  if confirm "Open the Ollama download page?"; then
    open_url "https://ollama.com/download"
  fi
  note "Optional helper after install:"
  note "  $HARNESS_ROOT/packages/agent-harness/scripts/setup-local-embeddings.ps1 -InstallOllama"
  note "  $HARNESS_ROOT/packages/agent-harness/scripts/setup-local-embeddings.sh"
  pause "Press Enter once Ollama is installed (or skip and install later)"
fi

# ── 6. Optional: Graphify ─────────────────────────────────────────────────
stage "Optional — Graphify"
say "Graphify adds structural code retrieval. Default deploy enables it;"
say "you can skip with --no-graphify or install tooling now."
USE_GRAPHIFY=1
INSTALL_GRAPHIFY=0
INSTALL_UV=0
if confirm "Enable Graphify for this project?"; then
  if confirm "Run Graphify setup during deploy (--install-graphify)?"; then
    INSTALL_GRAPHIFY=1
    if confirm "Allow installing uv if missing (--install-graphify-prerequisite)?"; then
      INSTALL_UV=1
    fi
  fi
else
  USE_GRAPHIFY=0
fi

# ── 7. Deploy ─────────────────────────────────────────────────────────────
stage "Deploy into the project"
DEPLOY_ARGS=(deploy --project "$PROJECT_PATH" --refresh)
[[ "$USE_OLLAMA" -eq 1 ]] && DEPLOY_ARGS+=(--ollama)
if [[ "$USE_GRAPHIFY" -eq 0 ]]; then
  DEPLOY_ARGS+=(--no-graphify)
else
  [[ "$INSTALL_GRAPHIFY" -eq 1 ]] && DEPLOY_ARGS+=(--install-graphify)
  [[ "$INSTALL_UV" -eq 1 ]] && DEPLOY_ARGS+=(--install-graphify-prerequisite)
fi
if [[ -f "$PROJECT_PATH/agent-harness.config.yaml" ]]; then
  warn "agent-harness.config.yaml already exists in the target project."
  if confirm "Replace it with --force?"; then
    DEPLOY_ARGS+=(--force)
  else
    warn "Deploy aborted — existing config left unchanged."
    SKIPPED+=("deploy (config already exists; re-run with --force if needed)")
    pause "Continue to dashboard instructions?"
    # Jump past deploy run
    DEPLOY_ARGS=()
  fi
fi
if (( ${#DEPLOY_ARGS[@]} )); then
  say "About to run:"
  note "node \"$CLI\" ${DEPLOY_ARGS[*]}"
  confirm "Run deploy now?" || { warn "Skipped deploy."; SKIPPED+=("deploy"); DEPLOY_ARGS=(); }
fi
if (( ${#DEPLOY_ARGS[@]} )); then
  node "$CLI" "${DEPLOY_ARGS[@]}"
  printf '  %s✓ deploy finished%s\n' "$GREEN" "$RESET"
  if [[ "$INITIALIZED_GIT_REPO" -eq 1 ]]; then
    # Local identity only if unset — avoids failing commit on machines without global git config.
    if ! git -C "$PROJECT_PATH" config --get user.email >/dev/null 2>&1; then
      git -C "$PROJECT_PATH" config user.email "agent-harness@localhost"
    fi
    if ! git -C "$PROJECT_PATH" config --get user.name >/dev/null 2>&1; then
      git -C "$PROJECT_PATH" config user.name "Agent Harness"
    fi
    git -C "$PROJECT_PATH" add -A
    if [[ -n "$(git -C "$PROJECT_PATH" status --porcelain 2>/dev/null || true)" ]]; then
      if git -C "$PROJECT_PATH" commit -m "chore: initial commit (agent-harness install)"; then
        git -C "$PROJECT_PATH" branch -M main 2>/dev/null || true
        printf '  %s✓ created initial commit on main%s (working tree clean for Start reflect)\n' "$GREEN" "$RESET"
      else
        warn "initial git commit failed — commit manually before Start reflect."
        SKIPPED+=("initial git commit")
      fi
    else
      note "nothing to commit after deploy"
    fi
  fi
fi
pause "Continue to dashboard startup?"

# ── 8. Start dashboard ────────────────────────────────────────────────────
stage "Start dashboard"
say "The dashboard prints a loopback URL with a one-time access token."
say "Open that exact URL (token is only valid for that ui process)."
note "cd \"$PROJECT_PATH\""
note "node \"$CLI\" ui"
note "CURSOR_API_KEY must be set in the same environment that runs ui."
if [[ -z "${CURSOR_API_KEY:-}" ]]; then
  warn "CURSOR_API_KEY is not set in this shell — set it before starting ui."
fi

finish

printf '  Next: start the dashboard from the target project.\n\n'
if [[ -f "$CLI" && -d "$PROJECT_PATH" ]] && confirm "Start the dashboard now in this terminal?"; then
  cd "$PROJECT_PATH"
  export CURSOR_API_KEY="${CURSOR_API_KEY:-}"
  exec node "$CLI" ui
fi
